POST https://pwa-arbeitsblatt-4.herokuapp.com/notify
Content-Type: application/json

{
    "message": "Das ist eine Nachricht."
}
###
POST http://localhost:3000/notify
Content-Type: application/json

{
    "message": "Das ist eine Nachricht."
}